name: Jest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm run test
